jenkins:
  systemMessage: "Jenkins bootstrapped automatically"

jobs:
  - script: >
      pipelineJob('sandbox') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/eleschynskyy/jenkins-framework')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }