jenkins:
  systemMessage: "Jenkins bootstrapped automatically"

security:
  scriptApproval:
    approvedSignatures:
      - "staticMethod jenkins.model.Jenkins getInstance"
      - "method jenkins.model.Jenkins getNode java.lang.String"
      - "method hudson.model.Node getNumExecutors"

jobs:
  - script: >
      pipelineJob('sandbox') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/eleschynskyy/jenkins-framework')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }