jenkins:
  systemMessage: "Jenkins bootstrapped automatically"

clouds:
    - kubernetes:
        name: "kubernetes"
        namespace: "sandbox"
        serverUrl: "https://kubernetes.default"
        jenkinsUrl: "http://jenkins.sandbox.svc.cluster.local:8080"
        containerCapStr: "10"
        templates:
          - name: "nft-agent"
            label: "nft"
            serviceAccount: "default"
            containers:
              - name: "jnlp"
                image: "jenkins/inbound-agent:latest"
                ttyEnabled: true
                args: "^${computer.jnlpmac} ^${computer.name}"

jobs:
  - script: >
      pipelineJob('sandbox') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/eleschynskyy/jenkins-framework')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }