apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard   # set if your cluster has a default or desired class
